# Generated by Django 3.2.6 on 2021-08-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_auto_20210829_1757"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="created_time",
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
