# Generated by Django 3.2.6 on 2021-09-12 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_contributor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="author",
            new_name="author_user_id",
        ),
    ]
